// <auto-generated />
using APIWorkGroup.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIWorkGroup.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230502065350_UpdateTB_01")]
    partial class UpdateTB_01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("APIWorkGroup.Models.Admin_TB", b =>
                {
                    b.Property<int>("Admin_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Admin_address")
                        .HasColumnType("longtext");

                    b.Property<string>("Admin_email")
                        .HasColumnType("longtext");

                    b.Property<string>("Admin_name")
                        .HasColumnType("longtext");

                    b.Property<string>("Admin_password")
                        .HasColumnType("longtext");

                    b.Property<string>("Admin_username")
                        .HasColumnType("longtext");

                    b.Property<int>("Status_id")
                        .HasColumnType("int");

                    b.Property<int>("Type_id")
                        .HasColumnType("int");

                    b.HasKey("Admin_id");

                    b.ToTable("admin_TBs");
                });
#pragma warning restore 612, 618
        }
    }
}
