// <auto-generated />
using APIStore.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIWorkGroup.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("APIStore.Model.Admin_TB", b =>
                {
                    b.Property<int>("Admin_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Admin_address")
                        .HasColumnType("longtext");

                    b.Property<string>("Admin_email")
                        .HasColumnType("longtext");

                    b.Property<string>("Admin_name")
                        .HasColumnType("longtext");

                    b.Property<string>("Admin_password")
                        .HasColumnType("longtext");

                    b.Property<int>("Admin_statusid")
                        .HasColumnType("int");

                    b.Property<int>("Admin_typeid")
                        .HasColumnType("int");

                    b.Property<string>("Admin_username")
                        .HasColumnType("longtext");

                    b.HasKey("Admin_id");

                    b.ToTable("admin_TBs");
                });
#pragma warning restore 612, 618
        }
    }
}
